name: bouh_supreme_udc_enterprise
description: "A new Flutter project."
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  vector_math: 2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/kml/
    - assets/kml/
    - assets/data/BOHUH_MASTER_PACKAGE.geojson
    - assets/data/targets_master.csv
    - assets/data/aoi_envelopes.csv
